name: Deploy Portfolio

on:
  push:
    branches: [master]

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}